In [1]:
import pandas as pd
import os

In [2]:
df_clients = pd.read_csv('seed_data/raw_customers.csv')

In [3]:
df_clients

,customer_id,customer_name,email,country,created_at
0,C0001,Noah Berg,noah.berg1@example.com,FR,2024-09-07
1,C0002,Lucas Rossi,lucas.rossi2@example.com,SE,2024-03-30
2,C0003,Nora Costa,nora.costa3@example.com,NL,2024-01-31
3,C0004,Olivia Dubois,olivia.dubois4@example.com,DE,2025-06-01
4,C0005,Aiden Berg,aiden.berg5@example.com,PT,2024-07-22
...,...,...,...,...,...
116,C0117,Hugo Dubois,hugo.dubois117@example.com,IT,2024-11-25
117,C0118,Lena Nilsson,lena.nilsson118@example.com,PL,2024-08-06
118,C0119,Clara Weber,clara.weber119@example.com,FI,2024-03-27
119,C0120,Hugo Moreau,hugo.moreau120@example.com,NO,2024-12-09
120,C0023,Sofia Santos,sofia.santos23@example.com,ES,2024-08-05

In [5]:
df_inv = pd.read_csv('seed_data/raw_invoices.csv')
df_inv

     invoice_id subscription_id invoice_date  amount currency  status
0       I000001          S00001   2024-10-20    29.0      EUR  failed
1       I000002          S00001   2024-11-20    29.0      EUR    paid
2       I000003          S00001   2024-12-20    29.0      EUR    paid
3       I000004          S00001   2025-01-20    29.0      EUR    paid
4       I000005          S00001   2025-02-20    29.0      EUR    paid
...         ...             ...          ...     ...      ...     ...
2850    I002851          S00174   2026-03-11   299.0      EUR    paid
2851    I002852          S00174   2026-04-11   299.0      EUR    paid
2852    I002853          S00174   2026-05-11   299.0      EUR    paid
2853    I002854          S00174   2026-06-11   299.0      EUR    paid
2854    I002855          S00174   2026-07-11   299.0      EUR    open

[2855 rows x 6 columns]

In [6]:
df_subs = pd.read_csv('seed_data/raw_subscriptions.csv')
df_subs

,subscription_id,customer_id,plan_name,monthly_price,start_date,end_date,status
0,S00001,C0001,starter,29.0,2024-10-20,NaN,active
1,S00002,C0002,starter,29.0,2024-04-01,NaN,active
2,S00003,C0003,starter,29.0,2024-02-29,NaN,active
3,S00004,C0004,scale,299.0,2025-07-15,NaN,active
4,S00005,C0005,scale,299.0,2024-09-04,NaN,active
...,...,...,...,...,...,...,...
170,S00171,C0118,starter,29.0,2024-09-22,NaN,active
171,S00172,C0119,growth,99.0,2024-04-24,2025-02-10,cancelled
172,S00173,C0119,starter,29.0,2025-01-18,NaN,active
173,S00174,C0120,scale,299.0,2025-01-11,NaN,active
174,S00006,C0006,starter,29.0,2025-05-23,NaN,active